# Generated by Django 3.0.7 on 2021-07-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=55)),
                ('subject', models.CharField(max_length=50)),
                ('mob_no', models.IntegerField()),
                ('dep_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
