# Generated by Django 3.0.7 on 2021-07-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetTimeTable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=10)),
                ('period', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'set_time_table',
                'managed': False,
            },
        ),
    ]
