# Generated by Django 3.0.7 on 2021-07-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=55)),
                ('qualification', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'hod',
                'managed': False,
            },
        ),
    ]
