# Generated by Django 3.0.7 on 2021-07-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'internal_time_table',
                'managed': False,
            },
        ),
    ]
